import avatar1 from "./assets/airpod1.jpeg";
import avatar from "./assets/istockphoto-1297832789-612x612.jpg";

export  const userData =  [
    {
        name: "Jan",
        "Active User": 4000,
    },
    {
        name: "Feb",
        "Active User": 3000,
    },
    {
        name: "Mar",
        "Active User": 5000,
    }, {
        name: "Apr",
        "Active User": 4000,
    },
    {
        name: "May",
        "Active User": 3000,
    },
    {
        name: "Jun",
        "Active User": 2000,
    },{
        name: "Jul",
        "Active User": 4000,
    },{
        name: "Aug",
        "Active User": 3000,
    },{
        name: "Sept",
        "Active User": 4000,
    },{
        name: "Oct",
        "Active User": 1000,
    },{
        name: "Nov",
        "Active User": 4000,
    },
    {
        name: "Dec",
        "Active User": 3000,
    },
];

export const productRows = [
    { id: 1,
        name: 'Apple Airpods',
        img: avatar1,
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    { id: 2,
        name: 'Apple Airpods',
        img: avatar1,
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    { id: 3,
        name: 'Apple Airpods',
        img: avatar1,
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    { id: 4,
        name: 'Apple Airpods',
        img: avatar1,
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    { id: 5,
        name: 'Apple Airpods',
        img: avatar1,
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    { id: 6,
        name: 'Apple Airpods',
        img: avatar1,
        stock: 123,
        status: "active",
        price: "$120.00",
    },

    { id: 7,
        name: 'Apple Airpods',
        img: avatar1,
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    { id: 8,
        name: 'Apple Airpods',
        img: avatar1,
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    { id: 9,
        name: 'Apple Airpods',
        img: avatar1,
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    { id: 10,
        name: 'Apple Airpods',
        img: avatar1,
        stock: 123,
        status: "active",
        price: "$120.00",
    },

]; export const userRows = [
    { id: 1,
        userName: 'Jon Snow',
        avatar: avatar,
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    { id: 2,
        userName: 'Jon Snow',
        avatar: avatar,
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    { id: 3,
        userName: 'Jon Snow',
        avatar: avatar,
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    { id: 4,
        userName: 'Jon Snow',
        avatar: avatar,
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    { id: 5,
        userName: 'Jon Snow',
        avatar: avatar,
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    { id: 6,
        userName: 'Jon Snow',
        avatar: avatar,
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },

    { id: 7,
        userName: 'Jon Snow',
        avatar: avatar,
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    { id: 8,
        userName: 'Jon Snow',
        avatar: avatar,
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    { id: 9,
        userName: 'Jon Snow',
        avatar: avatar,
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
    { id: 10,
        userName: 'Jon Snow',
        avatar: avatar,
        email: "jon@gmail.com",
        status: "active",
        transaction: "$120.00",
    },
];
export  const productData =  [
    {
        name: "Jan",
        "Sales": 4000,
    },
    {
        name: "Feb",
        "Sales": 3000,
    },
    {
        name: "Mar",
        "Sales": 5000,
    },
];